require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "completion"
-- require "lsp"
require "user.nvimtree"
require "user.telescope"
-- require "treesitter"
require "user.autopairs"
-- require "comment"
require "user.bufferline"
require "user.lualine"

